# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})${{ matrix.config.mkl && ' + MKL' || '' }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release'}
          - {os: windows-latest,  r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', mkl: true}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-26.04-arm, r: 'release'}
          - {os: ubuntu-26.04-arm, r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      MKL_THREADING_LAYER: GNU      # avoid conflicts between MKL and GNU OpenMP (ignored by non-MKL jobs)

    steps:
      - name: Check out package
        uses: actions/checkout@v3

      - name: Install Intel MKL     # this step only executes if mkl is set to true in the matrix configuration
        if: ${{ matrix.config.mkl == true }}
        run: |
          sudo apt-get update
          curl -s https://githubusercontent.com | sudo bash

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML, any::roxygen2
          needs: check

      - name: Document
        run: roxygen2::roxygenise(roclets = "rd")
        shell: Rscript {0}

      - name: Run R check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
